behaviors:
  BalanceAgent:
    trainer_type: ppo
    
    # NOW COMPATIBLE - 45 observations match pretrained model
    init_path: C:\Projects\RagdollBalanceRL_V2\results\balance_v2\BalanceAgent\BalanceAgent-3329141.pt

    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    keep_checkpoints: 10
    max_steps: 100000000
    time_horizon: 1000
    summary_freq: 10000
    checkpoint_interval: 500000
    threaded: false

torch_settings:
  device: cuda
